In [1]:
import numpy as np

## Soal 1 (membuat Tensor)

In [2]:
a= np.array([[23,50],[7,12]])
b= np.array([[57,67],[99,43]])
c= np.array([[75,21],[57,12]])
d= np.array([[87,26],[18,84]])

In [3]:
print(a)

[[23 50]
 [ 7 12]]


In [4]:
tensor = np.array([[a,b],[c,d]])
print(tensor)

[[[[23 50]
   [ 7 12]]

  [[57 67]
   [99 43]]]


 [[[75 21]
   [57 12]]

  [[87 26]
   [18 84]]]]


In [5]:
print(tensor.shape)

(2, 2, 2, 2)


## Soal 2 (Perkalian Matriks)

In [6]:
A = np.array([[23, 50, 19],
              [7, 12, 109],
              [57, 67, 98]])
B = np.array([[17],
              [22],
              [19]])

In [7]:
print(A)
print(B)

[[ 23  50  19]
 [  7  12 109]
 [ 57  67  98]]
[[17]
 [22]
 [19]]


In [8]:
# melihat ordo / shape matriks, perkalian yang bisa dilakukan adalah A . B

j = A @ B
print(j)

[[1852]
 [2454]
 [4305]]


## Soal 3 (Operasi Matriks)

In [9]:
A

array([[ 23,  50,  19],
       [  7,  12, 109],
       [ 57,  67,  98]])

### Transpose

In [10]:
p=A.T
print(p)

[[ 23   7  57]
 [ 50  12  67]
 [ 19 109  98]]


### Determinant

In [11]:
detA= np.linalg.det(A)
print(detA)

131344.0000000002


### Inverse

In [12]:
invA= np.linalg.inv(A)
print(invA)

[[-0.0466485  -0.02761451  0.03975819]
 [ 0.04208034  0.00891552 -0.01807467]
 [-0.00163692  0.0099662  -0.00056341]]


In [13]:
# percobaan, hasil kali dengan A adalah matriks indeks

q= A @ invA
print(q.round())

[[ 1. -0.  0.]
 [-0.  1.  0.]
 [ 0.  0.  1.]]
