In [1]:
import numpy as np

A = matriks, x = eigen vektor, L = eigen value

pasangan matriks dengan eigen vektor dan eigen valuenya akan memenuhi persamaan:

A x = L x

L = A @ x / x

In [67]:
A = np. array ([[1, -1],
               [6, 4]])
b = np.array([1,3])

In [44]:
A

array([[ 1, -1],
       [ 6,  4]])

In [68]:
b

array([1, 3])

In [69]:
A @ b / b

array([-2.,  6.])

Nilai elemen berbeda (-2 dan 6). Hasil operasi menunjukkan vektor B bukan merupakan eigen vektor matriks A.

In [70]:
np.linalg.eig(A)

(array([2.5+1.93649167j, 2.5-1.93649167j]),
 array([[-0.23145502+0.29880715j, -0.23145502-0.29880715j],
        [ 0.9258201 +0.j        ,  0.9258201 -0.j        ]]))

In [71]:
eig_val, eig_vec = np.linalg.eig(A)

eigen vektor matriks A

In [72]:
eig_vec

array([[-0.23145502+0.29880715j, -0.23145502-0.29880715j],
       [ 0.9258201 +0.j        ,  0.9258201 -0.j        ]])