## Gradien

- 3x + 4y = 5, data yang diolah adalah 3x + 4y - 5 

### Symbolic Method

In [1]:
import sympy as sy

In [2]:
x,y = sy.symbols('x y')
f= 3*x +4*y - 5
f

3*x + 4*y - 5

In [3]:
# Cara I

from sympy.tensor.array import derive_by_array
grad = derive_by_array(f, (x,y))
grad

[3, 4]

In [4]:
type(grad)

sympy.tensor.array.dense_ndim_array.ImmutableDenseNDimArray

In [5]:
# Cara II

f2= sy.Matrix([3*x+4*y-5])
par = sy.Matrix([x,y])
f3= f2.jacobian(par)
f3

Matrix([[3, 4]])

In [6]:
type(f3)

sympy.matrices.dense.MutableDenseMatrix

In [7]:
# Cara III

f4= sy.Matrix(grad)
f4

Matrix([
[3],
[4]])

In [8]:
type(f4)

sympy.matrices.dense.MutableDenseMatrix

### Numerical Method

In [9]:
import numpy as np

def f(x,y): 
  return 3*x + 4*y - 5

x=np.linspace(1,10)
y=np.linspace(1,10)

z=np.array( [[f(i,j) for i in x] for j in y] )

dx,dy=np.gradient(z)

In [10]:
z

array([[ 2.        ,  2.55102041,  3.10204082, ..., 27.89795918,
        28.44897959, 29.        ],
       [ 2.73469388,  3.28571429,  3.83673469, ..., 28.63265306,
        29.18367347, 29.73469388],
       [ 3.46938776,  4.02040816,  4.57142857, ..., 29.36734694,
        29.91836735, 30.46938776],
       ...,
       [36.53061224, 37.08163265, 37.63265306, ..., 62.42857143,
        62.97959184, 63.53061224],
       [37.26530612, 37.81632653, 38.36734694, ..., 63.16326531,
        63.71428571, 64.26530612],
       [38.        , 38.55102041, 39.10204082, ..., 63.89795918,
        64.44897959, 65.        ]])

In [11]:
dx

array([[0.73469388, 0.73469388, 0.73469388, ..., 0.73469388, 0.73469388,
        0.73469388],
       [0.73469388, 0.73469388, 0.73469388, ..., 0.73469388, 0.73469388,
        0.73469388],
       [0.73469388, 0.73469388, 0.73469388, ..., 0.73469388, 0.73469388,
        0.73469388],
       ...,
       [0.73469388, 0.73469388, 0.73469388, ..., 0.73469388, 0.73469388,
        0.73469388],
       [0.73469388, 0.73469388, 0.73469388, ..., 0.73469388, 0.73469388,
        0.73469388],
       [0.73469388, 0.73469388, 0.73469388, ..., 0.73469388, 0.73469388,
        0.73469388]])

In [12]:
dy

array([[0.55102041, 0.55102041, 0.55102041, ..., 0.55102041, 0.55102041,
        0.55102041],
       [0.55102041, 0.55102041, 0.55102041, ..., 0.55102041, 0.55102041,
        0.55102041],
       [0.55102041, 0.55102041, 0.55102041, ..., 0.55102041, 0.55102041,
        0.55102041],
       ...,
       [0.55102041, 0.55102041, 0.55102041, ..., 0.55102041, 0.55102041,
        0.55102041],
       [0.55102041, 0.55102041, 0.55102041, ..., 0.55102041, 0.55102041,
        0.55102041],
       [0.55102041, 0.55102041, 0.55102041, ..., 0.55102041, 0.55102041,
        0.55102041]])